name: Deploy CC App

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   # Allows you to run this workflow remotley from GitHub API 
  repository_dispatch:
    types: [deploy-api]
    inputs:
        # Change this value
        APP_NAME:
          description: 'Existing web app name to deploy to'
          required: true

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  DOTNET_VERSION: '3.1.x'           # set this to the dot net version to use
  WEBSITE_NAME: ''                  # this is going to be filed by querying the web apps in the resource group

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:

      # Checkout the repo
      - uses: actions/checkout@v3
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm ci 
          npm run build --if-present
        working-directory: "./Source/CompanyCommunicator/ClientApp"
        #--ignore-scripts

      # Run dotnet restore
      - name: dotnet restore
        run: |
          dotnet restore "./Source/CompanyCommunicator/Microsoft.Teams.Apps.CompanyCommunicator.csproj"

      # Run dotnet build 
      - name: dotnet build 
        run: |
          dotnet build "./Source/CompanyCommunicator/Microsoft.Teams.Apps.CompanyCommunicator.csproj" --configuration Release

      # Run dotnet publish
      - name: dotnet publish
        run: |
          dotnet publish "./Source/CompanyCommunicator/Microsoft.Teams.Apps.CompanyCommunicator.csproj" -c Release -o ${{env.DOTNET_ROOT}}/ccapp

      # Azure Login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Get the web app name
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            echo "WEBSITE_NAME="$(awk -F'.' '{gsub("\"", "", $1); print $1}' <<< $(az webapp list -g ${{ secrets.AZURE_RG }} --query [0].defaultHostName)) >> $GITHUB_ENV
      

      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.WEBSITE_NAME }} # Replace with your app name
          package: ${{env.DOTNET_ROOT}}/ccapp
